{{ if not .Values.database.existing }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.database.instances }}
  storage:
    size: {{ .Values.database.persistence.size }}
    storageClass: {{ .Values.database.persistence.storageClass }}
  bootstrap:
    initdb:
      database: {{ .Values.database.secret.database }}
      owner: {{ .Values.database.secret.username }}

{{ end }}